config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  devise_for :users
  root to: "home#index"
  resources :questions do
  	resources :answers
  end

  resources :users do
    member do
      post :follow
    end
  end
  resources :topics do
    member do
      post :follow
    end
  end
  
end

app/models/answer.rb
class Answer < ApplicationRecord

  validates :content, presence: true
  validates :content, uniqueness: { scope: [:question_id]}

	belongs_to :question
	belongs_to :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord

  validates :title, presence: true, uniqueness: true

	has_many :answers
	belongs_to :user
	belongs_to :topic
end

app/models/topic.rb
class Topic < ApplicationRecord

	validates :name, presence: true

	has_many :questions
	has_many :answers, through: :questions

	act_as_followee
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable

  has_many :questions
  has_many :answers

  act_as_followee
  act_as_follower


  def topics
    followees.where(followee_type: 'Topic')
  end

  def following
    followees.where(followee_type: 'User')
  end

end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController

  before_action :set_question, only: [:new, :create, :show, :edit, :update]
  before_action :set_answer, only: [:show, :edit, :update]

  def new
    @answer = @question.answers.build
  end

  def create
    @answer = @question.answers.build(answer_params)
    @answer.user_id = current_user.id

    respond_to do |format|
      if @answer.save
        format.html { redirect_to @question, notice: 'Question was successfully created.' }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render :new }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
  end

  def edit
  end

  def update
    respond_to do |format|
      if @answer.update(answer_params)
        format.html { redirect_to [@question, @answer], notice: 'Answer was successfully updated.' }
        format.json { render :show, status: :ok, location: [@question, @answer] }
      else
        format.html { render :edit }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    def set_question
      @question = Question.find(params[:question_id])
    end

    def set_answer
      @answer = @question.answers.find(params[:id])
    end

    def answer_params
      params.require(:answer).permit(:content)
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :authenticate_user!
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	@questions = Question.all
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:show, :edit, :update, :destroy]

  # GET /questions
  # GET /questions.json
  def index
    redirect_to root_path
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
  end

  # GET /questions/new
  def new
    @question = current_user.questions.build
  end

  # GET /questions/1/edit
  def edit
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = Question.new(question_params)
    @question.user_id = current_user.id

    respond_to do |format|
      if @question.save
        format.html { redirect_to @question, notice: 'Question was successfully created.' }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render :new }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'Question was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def question_params
      params.require(:question).permit(:title, :topic_id)
    end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
	def follow
    @topic = Topic.find(params[:id])
    if current_user.follow(@topic)
      flash[:notice] = "You started following #{@topic.name}"
    else
      flash[:alert] = 'Already following.'
    end
    redirect_to request.referer
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def follow
    @user = User.find(params[:id])
    if current_user == @user
    	flash[:alert] = "Can't follow youself."
    elsif current_user.follow(@user)
      flash[:notice] = "You started following #{@user.email}."
    else
      flash[:alert] = 'Already following.'
    end
    redirect_to request.referer
	end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/answers/_form.html.erb
<%= form_with(model: [@question, @answer], local: true) do |form| %>
  <% if @answer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@answer.errors.count, "error") %> prohibited this answer from being saved:</h2>

      <ul>
      <% @answer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/answers/edit.html.erb
<h1>Editing Question</h1>

<%= render 'form', answer: @answer %>

<%= link_to 'Show', [@question, @answer] %> |
<%= link_to 'Back', root_path %>

app/views/answers/new.html.erb
<h1>New Answer</h1>

<%= render 'form', question: @question %>

<%= link_to 'Back', root_path %>

app/views/answers/show.html.erb
<p>
  <strong>Content:</strong>
  <%= @answer.content %>
</p>

<p>
  <strong>User:</strong>
  <%= @answer.user.email %>
</p>

<% if @answer.user == current_user %>
  <%= link_to 'Edit Answer', edit_question_answer_path([@question, @answer]) %> |
<% end %>

<%= link_to 'Back', root_path %>

app/views/home/index.html.erb
<h1>Questions</h1>

<% @questions.each do |question| %>
  <%= link_to(question.title, question, class: 'question') %>
  <br>
<% end %>

<br>

<%= link_to 'New Question', new_question_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>QuoraNew</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <% if user_signed_in? %>
      <li>
      <%= link_to('Logout', destroy_user_session_path, method: :delete) %>        
      </li>
    <% else %>
      <li>
      <%= link_to('Login', new_user_session_path) %>  
      </li>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/questions/_form.html.erb
<%= form_with(model: question, local: true) do |form| %>
  <% if question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% question.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_area :title %>
  </div>

  <div class="field">
    <%= form.label :topic %>
    <%= form.select(:topic_id, Topic.all.collect {|u| [u.name, u.id]}, :prompt => 'Select') %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/questions/edit.html.erb
<h1>Editing Question</h1>

<%= render 'form', question: @question %>

<%= link_to 'Show', @question %> |
<%= link_to 'Back', root_path %>

app/views/questions/new.html.erb
<h1>New Question</h1>

<%= render 'form', question: @question %>

<%= link_to 'Back', root_path %>

app/views/questions/show.html.erb
<p>
  <strong>Content:</strong>
  <%= @question.title %>
</p>

<p>
  <strong>User:</strong>
  <%=button_to @question.user.email, follow_user_path(@question.user), class: 'follow_user', method: :post %>
</p>

<p>
  <strong>Topic:</strong>
  <%=button_to @question.topic.name, follow_topic_path(@question.topic), class: 'follow_topic', method: :post %>
</p>

<h4>Answers</h4>

<% @question.answers.each do |answer| %>
  <td><%= link_to(answer.content, [@question, answer], class: 'answer') %></td>
</br>
<% end %>

<%= link_to 'Add Answer', new_question_answer_path(@question) %>

<% if @question.user == current_user %>
  <%= link_to 'Edit Question', edit_question_path(@question) %> |
<% end %>

<%= link_to 'Back', root_path %>